### ISSUE TITLE
The default host

### ISSUE THREAD

**Issue by karl-police** [RoSocket/rosocket#9]
Is this http://66.94.113.204:6214

still being hosted? I see the website works, but what about the endpoint

If it does work, can we debug something. Something by default on that host doesn't work, that I works on the localhost instead.

For some reason it won't establish a connection to ``wss://irc-ws.chat.twitch.tv``, but if I host it locally it does

**Comment by sturmgeisty** [comment]
No, I lost access to that since long time ago. You can host it on a server of yours and it will work.
